app = 'jenosize-api'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.minimal'

[env]
  ENVIRONMENT = 'production'
  PYTHONPATH = '/app/src'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1