[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.ui"

[deploy]
startCommand = "./start-ui.sh"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services.variables]
ENVIRONMENT = "production"
PYTHONPATH = "/app/src"