"""Ultra-simple FastAPI app for Railway debugging"""
from fastapi import FastAPI

app = FastAPI(title="Jenosize API Test")

@app.get("/")
async def root():
    return {"message": "Railway deployment test successful!"}

@app.get("/health")
async def health():
    return {"status": "healthy"}

@app.post("/generate")
async def generate():
    return {
        "content": "This is a test article generated by the Railway deployment.",
        "success": True
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)